config/routes.rb
Depot::Application.routes.draw do
  get 'admin' => 'admin#index'
  
  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  get "sessions/create"
  get "sessions/destroy"

  resources :users
  
  resources :products do
    get :who_bought, on: :member
  end

  scope '(:locale)' do
    resources :orders
    resources :line_items
    resources :carts
    root 'store#index', as: 'store', via: :all
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pragprog Books Online Store</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
 <body class='<%= controller.controller_name %>'>
<div id="banner">
	<%= image_tag("logo.png") %>
	<%= @page_title || t('.title') %>
</div>
<div id="columns">
	<div id="side">
	<!-- UNTUK mengosongkan ganti ke semula dgn div#id cart -->
	<% if @cart %>
	<div id="cart">
	<%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
		<%= render @cart%>
	<% end %>
	<% end %>
	
	<ul>
		<li><%= link_to t('.home'), store_path%></li>
		<li><a href="#">Questions<%= t('.questions') %></a></li>
		<li><a href="#">News<%= t('.news') %></a></li>
		<li><a href="#">Contact<%= t('.contact') %></a></li>
		<li><%= link_to 'login',login_path %></li>
	</ul>
	<% if session[:user_id]%>
		<ul>
			<li><%= link_to 'Orders', orders_path %></li>
			<li><%= link_to 'Products', products_path %></li>
			<li><%= link_to 'Users', users_path %></li>
		</ul>
		<%= button_to 'logout', logout_path, method: :delete %>
	<% end %>
	</div>
	</div>
	
	<div id="main">
<%= yield %>
	</div></div>
</body>
</html>